aliases:
  - &restore-yarn-cache
    keys:
      - v1-yarn-cache-{{ arch }}-{{ checksum "yarn.lock" }}
      - v1-yarn-cache-{{ arch }}

  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
key: v1-yarn-cache-{{ arch }}-{{ checksum "yarn.lock" }}

version: 2
jobs:
  test:
    docker:
      - image: node:8
    working_directory: ~/guarantee
    steps:
      - restore-cache: *restore-yarn-cache
      - run: yarn install --non-interactive --cache-folder ~/.cache/yarn
      - save-cache: *save-yarn-cache
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  tests:
    jobs:
      - test
