version: 2
jobs:
  test:
    docker:
      - image: node:8
    working_directory: ~/guarantee
    steps:
      - run: yarn install
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  tests:
    jobs:
      - test
